# Generated by Django 5.2.7 on 2026-03-18 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cores_criadas', to=settings.AUTH_USER_MODEL)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cores_excluidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, max_length=25, null=True, verbose_name='setor')),
                ('data', models.DateField()),
                ('nome_ficha', models.CharField(max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_excluidas', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['-data', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='FichaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome_ficha', models.CharField(max_length=200)),
                ('setor', models.CharField(default='Injetora', max_length=50)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_inventario_excluidas', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Inventário',
                'verbose_name_plural': 'Fichas de Inventário',
                'ordering': ['-data', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCalcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo')),
                ('ativo', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cores', models.ManyToManyField(related_name='modelos', to='qualidade.cor')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_criados', to=settings.AUTH_USER_MODEL)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_excluidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Calçado',
                'verbose_name_plural': 'Modelos de Calçado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NomeOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_excluidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nome do Operador',
                'verbose_name_plural': 'Nomes dos Operadores',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ParteCalcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_excluidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parte do Calçado',
                'verbose_name_plural': 'Partes do Calçado',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('operador', 'Operador'), ('qualidade', 'Qualidade'), ('loja', 'Loja')], default='operador', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='TamanhoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número/Tamanho')),
                ('ativo', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='qualidade.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='qualidade.modelocalcado')),
            ],
            options={
                'verbose_name': 'Tamanho do Modelo',
                'verbose_name_plural': 'Tamanhos dos Modelos',
                'ordering': ['numero'],
                'unique_together': {('modelo', 'cor', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RegistroParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidades', models.JSONField(default=list)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='qualidade.ficha')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.partecalcado')),
            ],
            options={
                'verbose_name': 'Registro de Parte',
                'verbose_name_plural': 'Registros de Partes',
                'unique_together': {('ficha', 'parte')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pe_direito', models.IntegerField(default=0, verbose_name='Quantidade Pé Direito')),
                ('quantidade_pe_esquerdo', models.IntegerField(default=0, verbose_name='Quantidade Pé Esquerdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.cor')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='qualidade.fichainventario')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.modelocalcado')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.tamanhomodelo')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['modelo__nome', 'cor__nome', 'tamanho__numero'],
                'unique_together': {('ficha', 'modelo', 'cor', 'tamanho')},
            },
        ),
    ]
