# Generated by Django 5.2.7 on 2026-03-25 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMovimentacaoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_item', models.CharField(blank=True, max_length=255, null=True)),
                ('acao', models.CharField(choices=[('adicionar', 'Adicionado'), ('subtrair', 'Removido')], max_length=10)),
                ('lado', models.CharField(choices=[('PD', 'Pé Direito'), ('PE', 'Pé Esquerdo')], max_length=2)),
                ('quantidade_movimentada', models.IntegerField()),
                ('saldo_momento', models.IntegerField(help_text='Saldo total do item após a ação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='qualidade.fichainventario')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='qualidade.iteminventario')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
