# Generated by Django 5.2.7 on 2025-10-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecalcado',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partecalcado',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
