# Generated by Django 5.2.7 on 2025-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_partecalcado_excluido_partecalcado_excluido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
