# Generated by Django 5.2.7 on 2026-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_logmovimentacaov2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='tipo',
            field=models.CharField(blank=True, choices=[('producao', 'Produção'), ('perdas', 'Perdas'), ('reposicao', 'Reposição'), ('amostra', 'Amostra')], max_length=20, null=True, verbose_name='Tipo de Ficha'),
        ),
    ]
