# Generated by Django 5.2.7 on 2025-11-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0005_partecalcado_excluido_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_excluidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nome do Operador',
                'verbose_name_plural': 'Nomes dos Operadores',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
